openapi: 3.0.0
info:
  title: Codenames API
  version: 0.1.0
  description: API for the codenames game
  x-logo:
    url: >-
      https://d1wzvcwrgjaybe.cloudfront.net/repos/games/codenames-api/readme-repo-icon.png
    backgroundColor: '#FAFAFA'
    altText: Logo
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          description: Unique guid to identify the game
          type: string
        code:
          description: 'This game''s code, can be used by others to join'
          type: string
        started:
          description: Indicates whether the game has started or not
          type: boolean
        turn:
          description: Which team's turn it is to give clues and make guesses
          $ref: '#/components/schemas/Team'
        tiles:
          description: The tiles that players will provide clues and guesses for
          type: array
          items:
            $ref: '#/components/schemas/Tile'
        people:
          description: The people that are playing this game
          type: array
          items:
            $ref: '#/components/schemas/Person'
    CreatePersonRequest:
      type: object
      required:
        - name
      properties:
        name:
          description: This person's (code)name
          type: string
    Person:
      type: object
      properties:
        id:
          description: Unique guid to identify the person
          type: string
        name:
          description: This person's (code)name
          type: string
        role:
          description: This person's role
          $ref: '#/components/schemas/Role'
        team:
          description: The team this person belongs to
          $ref: '#/components/schemas/Team'
    Role:
      type: object
      enum:
        - SPYMASTER
        - SPY
    Team:
      type: object
      enum:
        - RED
        - BLUE
        - NEUTRAL
        - ASSASSIN
    Tile:
      type: object
      properties:
        id:
          description: Unique guid to identify the tile
          type: string
        word:
          description: The codename on this tile
          type: string
        selected:
          description: >-
            Indicates whether the tile has been selected (and so is known to all
            players)
          type: boolean
        team:
          description: The team this tile belongs to
          $ref: '#/components/schemas/Team'
servers:
  - url: 'https://yeq7szw1ak.execute-api.us-east-1.amazonaws.com/dev'
    description: Development server
paths:
  '/games/{gameId}/end':
    post:
      summary: End turn
      description: Create a new game of Codenames that others can join
      tags:
        - Game actions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePersonRequest'
      responses:
        '200':
          description: Newly created game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  '/games/{gameId}/guesses':
    post:
      summary: Make guess
      description: Create a new game of Codenames that others can join
      tags:
        - Game actions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePersonRequest'
      responses:
        '200':
          description: Newly created game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  '/games/{gameId}/start':
    post:
      summary: Start game
      description: Start an existing game
      tags:
        - Game actions
      responses:
        '200':
          description: The existing game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  '/games/{gameId}/people/{personId}/roles/{role}':
    put:
      summary: Update role
      description: Update the person's role on their team to the one specified
      tags:
        - Game setup
      parameters:
        - in: path
          name: gameId
          description: ID of the game this person is a part of
          required: true
          schema:
            type: string
        - in: path
          name: personId
          description: ID of the person changing roles
          required: true
          schema:
            type: string
        - in: path
          name: role
          description: Name of the role the person is choosing
          required: true
          schema:
            $ref: '#/components/schemas/Role'
      responses:
        '200':
          description: Game with updated information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  '/games/{gameId}/people/{personId}/teams/{team}':
    put:
      summary: Update team
      description: Update the user's team to the one specified
      tags:
        - Game setup
      parameters:
        - in: path
          name: gameId
          description: ID of the game this person is a part of
          required: true
          schema:
            type: string
        - in: path
          name: personId
          description: ID of the person changing roles
          required: true
          schema:
            type: string
        - in: path
          name: team
          description: Name of the team the person is joining
          required: true
          schema:
            $ref: '#/components/schemas/Team'
      responses:
        '200':
          description: Newly created game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  /games:
    post:
      summary: Create game
      description: Create a new game of Codenames that others can join
      tags:
        - Game setup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePersonRequest'
      responses:
        '200':
          description: Newly created game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  '/games/{code}/people':
    post:
      summary: Join game
      description: Join an existing game
      tags:
        - Game setup
      parameters:
        - in: path
          name: code
          description: User-friendly code of the game that is being joined
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePersonRequest'
      responses:
        '200':
          description: The existing game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '404':
          description: No game with that code was found
tags: []
