openapi: 3.0.0
info:
  title: Codenames API
  version: 0.1.0
  description: API for the codenames game
  x-logo:
    url: >-
      https://d1wzvcwrgjaybe.cloudfront.net/repos/games/codenames-api/readme-repo-icon.png
    backgroundColor: '#FAFAFA'
    altText: Logo
components: {}
paths:
  /games:
    post:
      summary: Create game
      description: Create a new game of Codenames that others can join
      tags:
        - Games
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameRequest'
      responses:
        '200':
          description: Newly created game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'
tags: []
